### ISSUE TITLE
RobotResults2RQM needs a feature to create Robot testscript link in RQM testcase

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/robotframework-robotlog2rqm#10]
Requirement from Amar Vishwanath:

A link to Robot testscript on Gerrit repo should be visible on RQM testcase from new comers easy to find the Robot script.

    Link to robot script on Gerrit should be defined as [Tags] information under Robot testcase.
    An additional attribute such as 'Robot file' will be added on RQM for link to robot script.
    Allow to update that information to existing testcase on RQM

 

Thank you,

Ngoan

**Comment by ngoan1608** [comment]
The implementation for this feature has been merged as this pull request #11 

Thank you,
Ngoan

**Comment by suprith5** [comment]
Hello Ngoan,

Request you to let us know once the Implementation is done.
Thanks in advance.

Thank you
Suprith

**Comment by ngoan1608** [comment]
> Hello Ngoan,
> 
> Request you to let us know once the Implementation is done. Thanks in advance.
> 
> Thank you Suprith

Hi @suprith5 ,

The implementation is done.
Please install the latest source package and try it from your side.

Thank you,
Ngoan

**Comment by suprith5** [comment]
Hello Ngoan,

Thanks for the feedback,

Could you please share the path/SW for latest source package

**Comment by ngoan1608** [comment]
Hi @suprith5 ,

Latest source is available in _develop_ branch of this repository:
https://github.com/test-fullautomation/robotframework-testresult2rqmtool

Please refer the [How to install](https://github.com/test-fullautomation/robotframework-testresult2rqmtool#how-to-install) in README file to install this package.
I have also updated the document for the new features, please refer [this document](https://github.com/test-fullautomation/robotframework-testresult2rqmtool/blob/develop/doc/_build/latex/RobotResults2RQM.pdf) for more details.

Thank you,
Ngoan

**Comment by suprith5** [comment]
Hello Ngoan,

Thank you.

**Comment by suprith5** [comment]
Hello Ngoan,

The RoboScript link is not seen in the RQM attribute after the running the commands.

Requesting your support for the same. Attached the Image of Script that we tried to update.

![ROBOScriptlink](https://user-images.githubusercontent.com/105191235/169027682-f8323771-3c8c-4765-9e92-8397a0937c60.PNG)

**Comment by ngoan1608** [comment]
Hi @suprith5 ,

You need contact the project administrator of your RQM project to add the additional attribute "**Robot File**" (case sensitive).
After that, that information will be reflect properly on your project area.

Thank you,
Ngoan
