### ISSUE TITLE
perpare robotlog2rqm for pypi

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/robotframework-robotlog2rqm#20]
please refer to [genpackagedoc ](https://github.com/test-fullautomation/python-genpackagedoc) and align your documentation and repository accordingly.

As soon as the pull request is merged I will setup publishing to pypi.

**Comment by test-fullautomation** [comment]
Hi Ngoan,
what is the status here?
Thank you,
 Thomas

**Comment by ngoan1608** [comment]
Hi Thomas,

I am updating the README and document together with the changes due to Holger's suggestion (Jira ticket ROBFW-346).

I will complete it and create pull request for you today.

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
solved with already merged #22
