### ISSUE TITLE
Some findings in documentation

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-robotlog2rqm#24]
[RobotLog2RQM.pdf](https://github.com/test-fullautomation/robotframework-robotlog2rqm/files/10559045/RobotLog2RQM.pdf)

**Comment by test-fullautomation** [comment]
Hi Ngoan,
please look into this.
This has lower priority than build, WebSite and Continous Test.
Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
Hi Ngoan,

what is the status of this issue?

Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
Hi Ngoan,
what is the status of this issue?
Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
Hi @ngoan1608 ,
what is the status of this issue?
Thank you,
 Thomas
