### ISSUE TITLE
Support for creating test suites (and possibly test plans)

### ISSUE THREAD

**Issue by maihuuthien** [test-fullautomation/robotframework-robotlog2rqm#30]
Currently, using the RobotLog2RQM python library, we can only create test cases on RQM. It would be nice if we can go higher up in the hierarchy:
- Create a test suite, then link test cases to the test suite.
- Create a test plan, then link test suites and other test cases to the test plan. (This feature is desired, but only optional, since elevated permissions might be required.)

**Comment by test-fullautomation** [comment]
Hi @ngoan1608 ,
what is the status of this issue?
Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
integrated in 0.12.1
