### ISSUE TITLE
feature to work with RQM server which is hosted behind the SSO system

### ISSUE THREAD

**Issue by ngoan1608** [test-fullautomation/robotframework-robotlog2rqm#34]
Hi,

`RobotLog2RQM` tool raises login issue when working with RQM server which is hosted behind the SSO (single sign on) system.
An authentication for SSO (similar to issue with testresultwebapp behind WAM) is required.

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
integrated in RobotFramework AIO 0.11.0
