### ISSUE TITLE
Failed to import test case which has SKIP state

### ISSUE THREAD

**Issue by ngoan1608** [test-fullautomation/robotframework-robotlog2rqm#38]
Hi,

Test case(s) which has `SKIP `status is failed to import to RQM with below error:
```
ERROR: Invalid Robotframework result state 'SKIP' of test 'RQM12'.
```
The mapping result for this status is missing.

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
integrated in 0.12.1
