### ISSUE TITLE
Not able to upload result to RQM with multiple parallel configurations (streams)

### ISSUE THREAD

**Issue by annettearpana31** [test-fullautomation/robotframework-robotlog2rqm#42]
Hi 
i am having 2 stream currently from the same project 

SW Test: Test  Plan: 1744: EnvD_SwQual_MAAS_PROD_PI24.2.0_003_Approval - Quality Management (bosch.com)
System Test: Test  Plan: 1745: EnvD_SysQual_MAAS_PROD_PI24.2.0_003_Approval - Quality Management (bosch.com)

I am able to upload to test plan 1744 but not to 1745.
Error reported has been added .

**Comment by ngoan1608** [comment]
Integrated in RobotFramework AIO 0.13.0
