### ISSUE TITLE
Name convention to set names for resources (TCER, Test Result, Suite Result)

### ISSUE THREAD

**Issue by dthieu125** [test-fullautomation/robotframework-robotlog2rqm#43]
Currently, we can only display 1 TSER due to default name - "TSER: <Test Suite Name>". When we upload new result, previous result will be overwritten. It is difficult to manage build versions and executions.
So, it would be nice if we can add some meta-data to define names for resources such as TCER, TSER, Test Result, Suite Result.
Thank you!

**Comment by ngoan1608** [comment]
Not yet started

**Comment by ngoan1608** [comment]
Integrated in RobotFramework AIO 0.13.1
